---
title: "suitsEDAsummary"
author: "kazuki yoda"
date: "2020/12/27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 紳士服専門店データに対するEDA

分析対象は2018年に行われた紳士服専門店における満足度調査である．
基本的にtidyverse系を利用する．

```{r}
library(tidyverse)
```


## 総合満足度のヒストグラムを見る

総合満足度はQ1に該当する．
まずはサマリーを見る．

```{r}
suits_18 %>%
  select(Q1) %>%
  summary()
```

全体的には満足していると考えられる．

```{r}
ggplot() +
  geom_histogram(data = suits_18, mapping = aes(x = Q1))
```

ヒストグラムだと関係性が見れていないので，棒グラフにする．

```{r}
ggplot() +
  geom_bar(data = suits_18, mapping = aes(x = Q1)) +
  theme_bw() +
  scale_y_continuous(breaks = seq(0,1000,100)) +
  scale_x_continuous(breaks = seq(0,10,1))
```

## 満足度の小項目

アンケート項目から抜き出し，Question項目にQ2_と含まれている行を抜き出してそのタイトルをリストで保存する．

```{r}
item_Q2 <- item_suits18_all %>%
  filter(grepl("Q2_", Question)) %>%
  select(Title)
```

アンケート項目を具体的に抽出する．

```{r}
item_Q2 <- item_suits18_all %>%
  filter(grepl("Q2_", Question)) %>%
  select(Title)
```

アンケート番号のみを抽出する．

```{r}
item_Q2_number <- item_suits18_all %>%
  filter(grepl("Q2_", Question)) %>%
  select(Question)
```


アンケート番号と具体的な質問を結合

```{r}
Q2_newlabel <- paste(item_Q2_number$Question, item_Q2$Title)
Q2_newlabel
```

```{r}
Q2 <- suits_18 %>%
  select(Q2_1:Q2_38)　%>%
  setNames(Q2_newlabel)

Q2
```

### ヒストグラム

小項目は順序尺度となっている．したがって，
